TARGET = sim
OBJS = $(CPPS:.cpp=.o)
CPPS = $(wildcard *.cpp)
CXX = g++
CXXFLAGS = -Wall -Wno-unknown-pragmas -Wno-unused-label -DSOFTWARE

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) -Wl,--stack,16777216 -o $@ $(OBJS)

clean:
	rm *.o
	rm $(TARGET)
